### PR TITLE
[FIX] product_multi_company: fix access to product variant

### PR DESCRIPTION
**Pull request by aayartsev**
Fix for this issue https://github.com/OCA/multi-company/issues/585

### CODE REVIEW

**Review by HekkiMelody — CHANGES_REQUESTED** [review]
**issue**: missing change to the `__init__.py` file.

**question**: This would add the field `company_ids` to product.product, which would then be independent of the same field on `product.template`. This way, wouldn't you risk having a mismatch in access rights between a `product.template` and its variants?

**Comment by aayartsev** [comment]
@aleuffre thanks, i add mised record in init file. 
As i can see this solution will not have risk because product variant record created from product template record, but product.product model did not have rules for multi-company features. It was a reason why we had mistake

**Comment by francesco-ooops** [comment]
@pedrobaeza what do you think about this?

**Review by pedrobaeza — CHANGES_REQUESTED** [review]
This doesn't seem the correct fix, and the linked issue is weird mentioning `company rule employee`, which is not related to this module.

**Comment by ilyasProgrammer** [comment]
@aleuffre @pedrobaeza please take a look at another solution: https://github.com/OCA/multi-company/pull/590

**Comment by francesco-ooops** [comment]
This can be closed then

**Pull request closed without merging**
