### PR TITLE
[16.0][MIG] account_invoice_consolidated

### PR DESCRIPTION
**Pull request by MS-OSI**
Account Invoice Consolidated
============================
This module allows organizations with multiples companies to transfer the
liability of a customer to another company and provide the customer with a
unique consolidated invoice to pay.

### CODE REVIEW

**Comment by Nikul-OSI** [comment]
@osi-scampbell @max3903 @MiquelRForgeFlow  Ready to review

**Comment by max3903** [comment]
@MS-OSI Can you squash the last 2 commits?

**Review by max3903 — APPROVED** [review]

**Comment by Nikul-OSI** [comment]
> @MS-OSI Can you squash the last 2 commits?

Yes squashed, Thank you.

**Pull request closed without merging**
