### PR TITLE
[12.0] IMP purchase_sale_inter_company allowing to create purchase orders from sales order

### PR DESCRIPTION
**Pull request by eLBati**

### CODE REVIEW

**Review by mrcast — COMMENTED** [review]
@eLBati : It seems that quantities set on generated purchase order and receipt picking are not correct.
step:
- in company A create a sale order for a product with quantity major then 1  with company B as Customer
- confirm sale order
- switch to company B
- in purchase order you will find a purchase order with company A as vendor
- the quantity in the purchase order and in the picking is set to 1

THANKS

**Comment by eLBati** [comment]
@mrcast thanks, fixed

**Review by mrcast — APPROVED** [review]
Functional test OK!

**Comment by eLBati** [comment]
@chafique-delli @alexis-via @carlosdauden @Yajo what do you think?

**Review by mrcast — APPROVED** [review]
Functional test ok!

**Comment by GSLabIt** [comment]
@eLBati is this ready to merge?

**Review by GSLabIt — APPROVED** [review]
LGTM

**Comment by eLBati** [comment]
> @eLBati is this ready to merge?

For me, it is

**Pull request merged**
