### PR TITLE
[14.0][IMP] product_supplierinfo_intercompany: create/update intercompany s…

### PR DESCRIPTION
**Pull request by ilyasProgrammer**
…upplier info on product create/update.

### CODE REVIEW

**Review by francesco-ooops — APPROVED** [review]
Functional ok!

Prior to this PR, creating a new product did not trigger supplierinfo creation (only updating intercompany pricelist would)

Also updating product sale price would not trigger update of supplierinfo (eg: with an intercompany pricelist line "all product -20%", if price of product A changed from 100 to 1000, supplierinfo price would still be 80 instead of 800)

@PierrickBrun, @sebastienbeau, @kevinkhao any feedback? 

Thanks!

**Review by elvise — APPROVED** [review]
LGTM!

**Comment by francesco-ooops** [comment]
@OCA/intercompany-maintainers could you review? thanks!

**Review by francesco-ooops — APPROVED** [review]
@OCA/intercompany-maintainers 

as per "usage", file, this PR adds the following: 

- a condition that supplierinfo will be created only for products where "Can be sold" and "Can be purchased" is set

- a supplierinfo will be created automatically for each new created product for which conditions are verified

- the supplierinfo will be updated when pricelist or product is updated

- note: supplierinfo is not visible when using the same Company as the one set in "Is Intercompany Supplier" pricelist, unless technical group "Access to all supplier info" is enabled in user.

**Comment by francesco-ooops** [comment]
@OCA/intercompany-maintainers gentle reminder

we think these are important changes to make the module work as intended

**Review by PierrickBrun — APPROVED** [review]
LGTM

**Comment by francesco-ooops** [comment]
@sbidoul could you take a look at why runboat link is not present in PR? 

I've seen this happen in other PRs as well, eg https://github.com/OCA/l10n-italy/pull/3081

**Comment by francesco-ooops** [comment]
@ilyasProgrammer can you rebase this one?

**Comment by ilyasProgrammer** [comment]
rebased

**Comment by francesco-ooops** [comment]
With latest improvement, we enforced the rule "supplierinfo is created for any product with "can be sold" and "can be purchased" set to active", regardless of the company of the user setting both fields to active

eg: C1 has intercompany pricelist applicable on all products > C2 user creates a new product which can be purchased but cannot be sold > save procut > C2 user activates "can be sold" on said product > supplierinfo with vendor C1 is created for this product

@OCA/intercompany-maintainers once again asking your review when possible :)

**Comment by sebastienbeau** [comment]
I am going to review it, this weekend.
Thanks for your contrinution

**Comment by francesco-ooops** [comment]
> I am going to review it, this weekend. Thanks for your contrinution

Thank you!

With lastest commits we also added a bridge module with product_multi_company to ensure intercompany supplierinfo are created only if product belongs to pricelist intercompany company, eg: 

C1 has intercompany pricelist applied on all products (10% discount)
C2 user creates product 1 belonging to C2 and C3 but not to C1
Supplierinfo with vendor C1 is not created for product 1

At the same time we made sure the supplierinfo is created as soon as C1 company is added to the product, and also in case no company is set for the product.

@ilyasProgrammer can you squash?

**Comment by francesco-ooops** [comment]
@sebastienbeau could you take a look?

**Comment by francesco-ooops** [comment]
@OCA/intercompany-maintainers could this be merged?

**Comment by francesco-ooops** [comment]
@JordiBForgeFlow could you take a look at this? thanks :)

**Comment by francesco-ooops** [comment]
@OCA/intercompany-maintainers we got 3 reviews on this and it implements important fixes in the flow, could you please merge?

**Comment by francesco-ooops** [comment]
@sebastienbeau gentle reminder, I think your positive review could get this merged

**Comment by francesco-ooops** [comment]
@Kev-Roche @PierrickBrun @rvalyi as I saw you approving a PR on same module

**Comment by francesco-ooops** [comment]
@PierrickBrun @sebastienbeau @kevinkhao any help to get this merged please?

**Comment by PierrickBrun** [comment]
Hi  @francesco-ooops ,

Can you stop tagging me on this PR ? I've already approved it.

You need to get a PSC/maintainer of the repo to merge it now that there is the correct number of approvals.

**Comment by francesco-ooops** [comment]
> Hi @francesco-ooops ,
> 
> Can you stop tagging me on this PR ? I've already approved it.
> 
> You need to get a PSC/maintainer of the repo to merge it now that there is the correct number of approvals.

@PierrickBrun sorry for being annoying, but can't you merge yourself as maintainer?

I don't like to bother people, but PSC for this repo don't seem to contribute here that much lately...

**Comment by PierrickBrun** [comment]
Ok, well I did not know I was added as a maintainer for this module...

**Comment by francesco-ooops** [comment]
Thanks for the effort @PierrickBrun , since there is a new module in this PR I'll ask for @pedrobaeza help here :)

**Pull request merged**
