### PR TITLE
[16.0][ADD] sale_purchase_inter_company

### PR DESCRIPTION
**Pull request by chafique-delli**
cc @sebastienbeau , @Kev-Roche

### CODE REVIEW

**Comment by chafique-delli** [comment]
@sebastienbeau , @Kev-Roche , can you review, please ?

**Comment by hitrosol** [comment]
Does this module plan to be compatible with the stock type product as well ?

I tried this on runboat. I installed the Inventory to test as a stock type Product.
I have checked the Purchase from Sale, put Michell Admin as Intercompany Purchase User. 
Create Sales Order, put the qty and specific unit price then confirm the Sales Order.
Result.
- The Unit Price become 0. --> It supposed to be the unit price as set in the Quotation.
- The Purchase Order in the Vendor Company created with correct qty and Unit Price is 0 as well. --> if the Unit price in Sales Order were correct, then the unit price in Purchase Order should show the same amount.

**Comment by chafique-delli** [comment]
> Does this module plan to be compatible with the stock type product as well ?
> 
> I tried this on runboat. I installed the Inventory to test as a stock type Product. I have checked the Purchase from Sale, put Michell Admin as Intercompany Purchase User. Create Sales Order, put the qty and specific unit price then confirm the Sales Order. Result.
> 
> * The Unit Price become 0. --> It supposed to be the unit price as set in the Quotation.
> * The Purchase Order in the Vendor Company created with correct qty and Unit Price is 0 as well. --> if the Unit price in Sales Order were correct, then the unit price in Purchase Order should show the same amount.

This module is compatible with the service type product i.e. when you do not want to depend on the Inventory module.
For the stock type product, it is the sale_purchase_stock_inter_company module: https://github.com/OCA/multi-company/pull/463

**Comment by jumeldi74** [comment]
Please add an unit test to run the uncovered function mentioned by codecov

**Comment by jumeldi74** [comment]
> Please add an unit test to run the uncovered function mentioned by codecov

If you don't mind, I'll add it

**Comment by chafique-delli** [comment]
> If you don't mind, I'll add it

Yes, I do. Thank you for your time.

**Comment by chafique-delli** [comment]
@kev-roche, @sebastienbeau , @metaminux

**Comment by legalsylvain** [comment]
Any review @kev-roche, @sebastienbeau , @metaminux  ?

**Comment by Kev-Roche** [comment]
Hello @chafique-delli , I made a fix here, what do you think ? https://github.com/akretion/multi-company/pull/14

**Pull request closed without merging**
