### PR TITLE
[15.0] [MIG] product_tax_multicompany_default

### PR DESCRIPTION
**Pull request by celm1990**

### CODE REVIEW

**Comment by celm1990** [comment]
@pedrobaeza can you review build, i see error
image

this repo is not ready for V15????

**Comment by pedrobaeza** [comment]
runbot is no longer valid for v15. Now it's used runbo**a**t. @sbidoul @gurneyalex can you please deactivate runbot for the branches where runboat is activated for avodiging these confusions?

/ocabot migration product_tax_multicompany_default

**Comment by celm1990** [comment]
somebody can help me review this PR?
ping @OCA/oca-members  @OCA/intercompany-maintainers

**Review by gurneyalex — APPROVED** [review]

**Review by dreispt — APPROVED** [review]

**Pull request merged**
