### PR TITLE
14.0 [MIG] OCA: mail_multicompany

### PR DESCRIPTION
**Pull request by rodrigoascencio**
followed the OCA guidelines to migrate the mail_multicompany to 14.0

### CODE REVIEW

**Comment by rodrigoascencio** [comment]
@jesusVMayor  hi if you have the chance, could you please review my PR?

**Comment by hugho-ad** [comment]
@moylop260

could you review it please

**Comment by moylop260** [comment]
@hugho-ad 
I'm not in context about this module

If you agree just comment and approve, please

**Review by hugho-ad — APPROVED** [review]

**Pull request merged**
