### PR TITLE
[16.0][MIG] purchase_sale_stock_inter_company: Migration to 16.0

### PR DESCRIPTION
**Pull request by JordiBForgeFlow**
Supersedes https://github.com/OCA/multi-company/pull/446

### CODE REVIEW

**Comment by chafique-delli** [comment]
@JordiBForgeFlow , can you rebase.

**Comment by legalsylvain** [comment]
Hi @JordiBForgeFlow, could you take a look on red CI ?

**Comment by JordiBForgeFlow** [comment]
@legalsylvain the CI is now green.

**Review by LoisRForgeFlow — APPROVED** [review]
LGTM

**Review by JordiMForgeFlow — APPROVED** [review]
LGTM 👍

**Comment by legalsylvain** [comment]
/ocabot merge nobump

Thanks !

**Pull request merged**
