### PR TITLE
[12.0][BKP] Backport from 14.0 to 12.0 for mail_multicompany

### PR DESCRIPTION
**Pull request by quentinDupont**
Changes are in this commit : https://github.com/OCA/multi-company/commit/276da1604b3726e554a70d7baa0ddbab0c58b04e and https://github.com/OCA/multi-company/pull/482/commits/e6661a2d9a7ce395d0221588fccf9e1370996792

Behaviour change from 14.0 or 16.0 : if a SMTP server is set without company_id, it can be used for all companies → priority is the most important criteria.

### CODE REVIEW

**Review by legalsylvain — APPROVED** [review]
Diff review. LGTM. Thanks ! 

Original developer : @jesusVMayor
Module contributors : @Cedric-Pigeon, @ValentinVinagre, @rodrigoascencio

Could you take a look ?

**Review by hparfr — APPROVED** [review]

**Review by JorgeQuinteros — APPROVED** [review]
LGTM! Technical Review

**Comment by quentinDupont** [comment]
:up: use in prod since 4 month and works well

**Comment by legalsylvain** [comment]
@JordiBForgeFlow could you merge this one ? 

thanks !

**Pull request merged**
