### PR TITLE
[14.0][MIG]account_payment_other_company.

### PR DESCRIPTION
**Pull request by hpatelserpentcs**
@patrickrwilson 
Migrated.
Improved the UT and Travis.

### CODE REVIEW

**Comment by patrickrwilson** [comment]
Hello @OCA/community-maintainers , anyone know why this runbot is failing? Error log shows: 
Unable to find image 'oca-multi-company:6fbdfc0_env_1_job_1' locally
docker: Error response from daemon: pull access denied for oca-multi-company, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
See 'docker run --help'.

**Comment by dreispt** [comment]
Don't mind Runbot. Travis is green, that's where the tests are.

**Comment by max3903** [comment]
@Urvisha-OSI  Can you fix this PR?

**Comment by Urvisha-OSI** [comment]
> @Urvisha-OSI Can you fix this PR?

@max3903 this PR issue is fixed

**Review by max3903 — APPROVED** [review]

**Pull request merged**
