### PR TITLE
14.0 product supplier intercompany

### PR DESCRIPTION
**Pull request by sebastienbeau**
This PR add the possibility to auto generate supplier info in multi company context

Example : In multi company if a Company A sell product (based on a pricelist) supplier info will be automatically generated (and sync) in the company B.

- [x] https://github.com/OCA/product-attribute/pull/785

### CODE REVIEW

**Comment by sebastienbeau** [comment]
@Kev-Roche can you fix it, thanks for you help

**Comment by Kev-Roche** [comment]
cc @sebastienbeau, it's done !

**Review by kevinkhao — APPROVED** [review]

**Comment by kevinkhao** [comment]
@sebastienbeau @Kev-Roche we will have an easier time by merging this fast

**Comment by sebastienbeau** [comment]
@bealdav @florian-dacosta @bguillot @PierrickBrun can you review?

**Review by Kev-Roche — APPROVED** [review]
LGTM

**Pull request merged**
