### PR TITLE
[MIG] stock_intercompany: Migration to 16.0

### PR DESCRIPTION
**Pull request by yankinmax**

### CODE REVIEW

**Comment by ivs-cetmix** [comment]
Hi @yankinmax, thank you for your contribution!  Could you please rebase your PR? We would like to do functional and code reviews

**Comment by angelinaanaki** [comment]
The code looks good to me. During the functional tests, I noticed that the 'qty_done' field of stock.move.line isn't being copied to the incoming picking. I'm uncertain whether this is intentional or a bug, as the logic for copying the stock.move.line is the same in version 15.0.

**Comment by ivs-cetmix** [comment]
> The code looks good to me. During the functional tests, I noticed that the 'qty_done' field of stock.move.line isn't being copied to the incoming picking. I'm uncertain whether this is intentional or a bug, as the logic for copying the stock.move.line is the same in version 15.0.

This is a migration PR so we are copying all the logic "as is". If any changes are needed they can be done later in separate PRs

**Review by angelinaanaki — APPROVED** [review]

**Review by ivs-cetmix — APPROVED** [review]
Functional OK

**Comment by ivs-cetmix** [comment]
Hey @OCA/intercompany-maintainers could you have a look at this please? We would like to have it merged to add some new features afterwards

**Pull request merged**
