### PR TITLE
[16.0][MIG] purchase sale inter company: Migration to 16.0 

### PR DESCRIPTION
**Pull request by chafique-delli**
cc @sebastienbeau , @Kev-Roche

### CODE REVIEW

**Review by Kev-Roche — APPROVED** [review]
LGTM

**Comment by chafique-delli** [comment]
@sebastienbeau , can you review, please ?

**Comment by jumeldi74** [comment]
I think the issue of this module is, need to be in one branch with sale_purchase_inter_company, so that testing of all function can be covered. CMIIW

**Comment by JordiMForgeFlow** [comment]
Hi @chafique-delli, it looks like it has been superseded in https://github.com/OCA/multi-company/pull/513

**Comment by pedrobaeza** [comment]
Yes, that's is, sorry. As you didn't put the module name correctly in the PR title, a search over the open pull request didn't return this one. Closing. Please feel free to review the merged one and add any comment.

**Comment by chafique-delli** [comment]
> Yes, that's is, sorry. As you didn't put the module name correctly in the PR title, a search over the open pull request didn't return this one. Closing. Please feel free to review the merged one and add any comment.

@pedrobaeza , I was unpleasantly surprised to see that another PR created recently for the same module was merged immediately. While my PR was awaiting reviews.

**Comment by pedrobaeza** [comment]
As said, we search for existing migration, but yours didn't appear due to the incorrect PR title, and thus, we proceed with our usual flow: do the migration, and review ourselves (but doing it properly, not only "approving" it), without waiting for spontaneous reviewers. You can adopt such flow in your company, which is healthier, and also scale in PSC/maintainer roles for being able to mark the module in the migration issue, or merge the PR.

**Pull request closed without merging**
