### PR TITLE
[ADD] module inter_company_rules

### PR DESCRIPTION
**Pull request by chafique-delli**
This module has been backported from Odoo v9.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Thanks for the backport. Can you please check the tests that are red?

**Comment by pedrobaeza** [comment]
I don't know why runbot is not launching a new build. @gurneyalex, any hint?

**Comment by gurneyalex** [comment]
@pedrobaeza the runbot is not configured on that repository. I'll fix this.

**Comment by pedrobaeza** [comment]
Thanks. Can you point me to the steps to make the same with odoomrp-wip and odoomrp-utils branches?

**Comment by gurneyalex** [comment]
@pedrobaeza off topic. I'm moving this to contributors mailing list

**Comment by pedrobaeza** [comment]
I'm closing and opening again to see if runbot makes the build

**Comment by pedrobaeza** [comment]
No, it seems that it doesn't rebuild runbot. @chafique-delli, can you check why the build is red?

**Comment by laetitia-gangloff** [comment]
Hello,

what is the status of this PR ?

I look for something similar but in V7, should I backport this ?

**Comment by alexis-via** [comment]
I worked quite a lot on this PR yesterday and fixed important issue. Please read the README.rst to understand a very important thing on taxes and product_id_change.

I'll try to find time to split this module in 2: one "base" module that only depends on "account" to have the inter-company rules on invoices, and a second module that depends on sale and purchase that adds support for inter-company rules on sale.order and purchase.order. I think it's important, in particular for the service companies that don't want to install the stock module (because purchase depends on stock).

**Comment by alexis-via** [comment]
Time to decide the name of the 2 "splitted" modules ; I propose:
inter_company_rule_invoice
inter_company_rule_sale_purchase
Are you OK with these names ?

**Comment by pedrobaeza** [comment]
Isn't better _inter_company_rule_account_ to follow standard "app" naming?

The others can be _inter_company_rule_sale_ and _inter_company_rule_purchase_ as always, and maybe _inter_company_rule_sale_stock_ if needed.

**Comment by eLBati** [comment]
@alexis-via @chafique-delli Hi
I fixed a problem with taxes, tests and flake8 at
https://github.com/akretion/multi-company/pull/2

Please take a look, thanks

For me, the module can be merged as is (single module version)

**Comment by eLBati** [comment]
Thanks @bealdav , in the meantime I found another issue. please see https://github.com/akretion/multi-company/pull/3

**Review by eLBati — APPROVED** [review]

**Comment by pedrobaeza** [comment]
What about the singular renaming?

**Comment by eLBati** [comment]
@pedrobaeza do you mean `inter_company_rule`?

**Comment by pedrobaeza** [comment]
Yeah, that's it: https://github.com/OCA/maintainer-tools/blob/master/CONTRIBUTING.md#modules, and it's another way to differentiate from Odoo one.

**Comment by eLBati** [comment]
@pedrobaeza in this case , there are several rules and the focus of the module is precisely to handle several inter company rules, so the plural seems more clear to me.

@alexis-via @chafique-delli @bealdav what do you think?

**Comment by pedrobaeza** [comment]
It's a general rule, not attached to any meaning. It even applies to `sale` module, that can be `sales`. Please see https://github.com/OCA/maintainer-tools/blob/master/CONTRIBUTING.md#modules

**Comment by chafique-delli** [comment]
Hi, as announced by @alexis-via  on January 12, we have splitted the module in two modules (purchase_sale_inter_company and account_invoice_inter_company) because we think it's better for the reasons given by @alexis-via .
View PR for purchase_sale_inter_company: https://github.com/OCA/multi-company/pull/31
View PR for account_invoice_inter_company: https://github.com/OCA/multi-company/pull/32

**Comment by bealdav** [comment]
@eLBati, @chafique-delli solve the problem ;-) 
But in a generally perspective, we can distinguish module technical name here 'inter_company_rule' and user friendly name 'Inter Company Rules'.
The first is singular, the second as you want according to spelling or pronunciation difference (and can be changed), no problem
95% modules are singular: it's an implicit rule
For my part I'm yet more convinced by singular form than pedro which think it's better to name mrp_operations_mymodule than mrp_operation_mymodule (according to existing mrp_operations)
I think no plural should propagated, and Pedro not. 
Sure than in the 2 next years i'll converted him to my opinion for the better, but not today, I'm sad like you.
Yes democraty is difficult ;-)
my 2 cents

**Comment by pedrobaeza** [comment]
Closing as there are new PRs

**Pull request closed without merging**
