### PR TITLE
[14.0][MIG]account_move_multi_company

### PR DESCRIPTION
**Pull request by hpatelserpentcs**
@patrickrwilson 
Migrated in 14.0
    > account_move_multi_company

### CODE REVIEW

**Comment by hpatelserpentcs** [comment]
Travis issue is coming because of this module depend on account_invoice_consolidated module and this is not in 14.0 addons [https://github.com//pull/284]

**Comment by patrickrwilson** [comment]
@hpatelserpentcs The dependency has been merged. Can you take a look at this again and make green? Thanks.

**Comment by hpatelserpentcs** [comment]
> @hpatelserpentcs The dependency has been merged. Can you take a look at this again and make green? Thanks.

Yes, I will update it.
Thanks

**Review by patrickrwilson — APPROVED** [review]
Installed and performed basic tests. Seems to work as intended. LGTM

**Comment by patrickrwilson** [comment]
@osi-scampbell can you review please?

**Comment by max3903** [comment]
@Freni-OSI Can you fix this PR?

**Review by max3903 — APPROVED** [review]

**Comment by max3903** [comment]
@Urvisha-OSI Can you fix this PR please?

**Comment by Urvisha-OSI** [comment]
> @Urvisha-OSI Can you fix this PR please?

@max3903 this PR issue is solved

**Pull request closed without merging**
