### PR TITLE
[MIG][14.0] partner_multi_company

### PR DESCRIPTION
**Pull request by ilyasProgrammer**

### CODE REVIEW

**Review by francesco-ooops — APPROVED** [review]
supersedes #349 

functional ok!

**Review by elvise — APPROVED** [review]
LGTM

**Comment by francesco-ooops** [comment]
@OCA/intercompany-maintainers when you can :)

**Comment by francesco-ooops** [comment]
@OCA/intercompany-maintainers can this be merged?

**Comment by francesco-ooops** [comment]
@OCA/intercompany-maintainers migration review please :)

**Comment by matteoopenf** [comment]
@pedrobaeza  is possibible to merge?

**Comment by matteoopenf** [comment]
> /ocabot migration partner_multi_company /ocabot merge nobump

thank you

**Pull request merged**
