### PR TITLE
[FIX] [10.0] Travis configuration

### PR DESCRIPTION
**Pull request by thomaspaulb**
Update Travis configuration because of [this PR](https://github.com/OCA/multi-company/pull/156) failing and inspired by [this template](https://github.com/OCA/maintainer-quality-tools/blob/master/sample_files/.travis.yml)

### CODE REVIEW

**Comment by thomaspaulb** [comment]
@pedrobaeza Is it possible to fast-track this, so that I can rebase #156 and run my tests there? They are now not running.

**Comment by pedrobaeza** [comment]
This is still in red I'm afraid

**Comment by thomaspaulb** [comment]
It is, but that is no reason to be afraid: this fix is just meant to make Travis run tests again - it is now not running because of errors in the Travis configuration. When this is fixed, I will be working on making my tests run successfully in #156 (short term) and making the whole branch green in #159 (long term). Problem is that the work on #156 is now blocked by non-functional Travis.

**Comment by pedrobaeza** [comment]
OK, merging manually.

**Comment by thomaspaulb** [comment]
Thanks.

**Pull request merged**
