### PR TITLE
[13.0][FIX] base_multi_company: Make company_id writeable again

### PR DESCRIPTION
**Pull request by pedrobaeza**
Not being writeable, we have warnings on constraints over this field (it's used for example in `sale` module for `product.template` model).

Giving an inverse to the field, we avoid this problem and give compatibility to any other module that writes this field.

A little patch on `_name_search` is also provided.

@Tecnativa

### CODE REVIEW

**Review by chienandalu — APPROVED** [review]

**Review by AaronHForgeFlow — APPROVED** [review]
:+1:

**Review by LoisRForgeFlow — APPROVED** [review]
LGTM :+1:

**Comment by LoisRForgeFlow** [comment]
@pedrobaeza will you forwardport this to v14?

**Comment by pedrobaeza** [comment]
The module is not yet migrated.

**Pull request merged**
