### PR TITLE
[12.0] - add multi-company management to calendar event

### PR DESCRIPTION
**Pull request by sbejaoui**

### CODE REVIEW

**Review by RobinetDenisAcsone — APPROVED** [review]
LGTM

**Comment by qgroulard** [comment]
+1 :+1:

**Review by qgroulard — APPROVED** [review]

**Comment by sbejaoui** [comment]
@OCA/core-maintainers , This PR is ready to merge

**Comment by elvise** [comment]
hi, any good news for merge?
how can i help for this task...?

**Comment by sbejaoui** [comment]
@OCA/core-maintainers , This PR is ready to merge

**Pull request merged**
