### PR TITLE
[10.0][IMP] stock_production_lot_multi_company: Edit SQL constraint including company

### PR DESCRIPTION
**Pull request by SimoRubi**
Fix https://github.com/OCA/multi-company/issues/117

### CODE REVIEW

**Review by eLBati — APPROVED** [review]

**Review by tafaRU — APPROVED** [review]

**Comment by SimoRubi** [comment]
@OCA/intercompany-maintainers could you please check? Thanks
Note that Travis fails as it is failing in 10.0.

**Review by gurneyalex — APPROVED** [review]

**Comment by gurneyalex** [comment]
@sbidoul @pedrobaeza any suggestion regarding merging in a red branch with ocabot?

**Comment by sbidoul** [comment]
@gurneyalex Such as /ocabot merge-even-if-its-red-i-know-what-i-am-doing ?
I don't know... is it not better to make the branches green than investing in a bot workaround?

**Comment by gurneyalex** [comment]
@sbidoul I agree on the principle... I'll try and do this. The multi company + serial number is currently hitting me pretty hard on a 12.0 instance, so I'm forward porting this PR to 12.0 (and migrating the related module too) and forward porting this to 11.0 too while I'm on it. I'll try and fix travis on multi-company/10.0  but this may take some time while this fix is much needed (but not by me...)

**Comment by pedrobaeza** [comment]
If you want to merge a failed PR, just merge the PR without using the bot, isn't it?

**Comment by tafaRU** [comment]
@gurneyalex would you do the honors to manually merge or can I proceed?

**Comment by SimoRubi** [comment]
@tafaRU @gurneyalex can this be merged? Thanks

**Comment by SimoRubi** [comment]
@OCA/intercompany-maintainers can you please check this? Thanks

**Comment by tafaRU** [comment]
@SimoRubi I was wrong, I cannot merge it. Sorry.

**Comment by SimoRubi** [comment]
@OCA/intercompany-maintainers can I do anything to help this PR being merged?

**Comment by pedrobaeza** [comment]
Travis is red, but let's see if rebasing works:

/ocabot merge

**Comment by SimoRubi** [comment]
I see `10.0` is red too (https://travis-ci.org/OCA/multi-company/branches), so I don't think rebasing will help..
As I said in https://github.com/OCA/multi-company/pull/118#issuecomment-448146114, the error for the travis of this PR is the same as `10.0`, so hopefully I'm not introducing any new error :P

Maybe we should focus on fixing `10.0`, but I think @gurneyalex is already working on this (based on https://github.com/OCA/multi-company/pull/118#issuecomment-510471713)

**Comment by SimoRubi** [comment]
@gurneyalex are you or someone else working on a fix to `10.0` branch? Otherwise I can try to look into it

**Comment by SimoRubi** [comment]
Created https://github.com/OCA/multi-company/issues/188 to keep track of `10.0` issue.

**Comment by SimoRubi** [comment]
@OCA/community-maintainers  runbot here is failing with message (https://runbot.odoo-community.org/runbot/static/build/3434620-118-88c5a9/logs/job_20_test_all.txt):
> Unable to find image 'oca-multi-company:88c5a97_env_2_job_1' locally
docker: Error response from daemon: pull access denied for oca-multi-company, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
See 'docker run --help'.

and `base log` is fine (https://runbot.odoo-community.org/runbot/static/build/3434620-118-88c5a9/logs/job_10_test_base.txt)

Can someone please take a look?
Thanks!

**Pull request merged**
