### PR TITLE
[ADD] multicompany_configuration

### PR DESCRIPTION
**Pull request by etobella**
This module simplifies the process of configuration of partners, products and product categories. It adds a new form that is opened with a button that allows you to edit all the company dependent fields at the same time.

https://user-images.githubusercontent.com/28590170/202043126-4517d1f7-25a0-487e-a29b-fc280d6c0277.mp4

As a next step, would be great to add some tests and maybe improving the view by using notebooks or something similar.

### CODE REVIEW

**Review by rafaelbn — COMMENTED** [review]
In res.partner I got an Odoo Server Error

imagen

```
Error:


Traceback:
Error: value.replace is not a function
parseNumber@http://oca-multi-company-14-0-pr407-33a482e07a13.runboat.odoo-community.org/web/content/435-a6c4f90/web.assets_backend.js:1074:164
parseInteger@http://oca-multi-company-14-0-pr407-33a482e07a13.runboat.odoo-community.org/web/content/435-a6c4f90/web.assets_backend.js:1090:52
_render/</company_data<@http://oca-multi-company-14-0-pr407-33a482e07a13.runboat.odoo-community.org/web/content/435-a6c4f90/web.assets_backend.js:6070:70
_.collect@http://oca-multi-company-14-0-pr407-33a482e07a13.runboat.odoo-community.org/web/content/434-577e17b/web.assets_common.js:109:270
_render/<@http://oca-multi-company-14-0-pr407-33a482e07a13.runboat.odoo-community.org/web/content/435-a6c4f90/web.assets_backend.js:6068:180
_.forEach@http://oca-multi-company-14-0-pr407-33a482e07a13.runboat.odoo-community.org/web/content/434-577e17b/web.assets_common.js:108:566
_render@http://oca-multi-company-14-0-pr407-33a482e07a13.runboat.odoo-community.org/web/content/435-a6c4f90/web.assets_backend.js:6066:260
start/<@http://oca-multi-company-14-0-pr407-33a482e07a13.runboat.odoo-community.org/web/content/435-a6c4f90/web.assets_backend.js:910:1417
```

**Review by fcvalgar — APPROVED** [review]
Functional review ok. 

Thank you @etobella.

**Comment by fcvalgar** [comment]
internal @moduon MT-1927

**Review by rafaelbn — APPROVED** [review]
Thank you! A new hope!

**Comment by rafaelbn** [comment]
@victoralmau @pedrobaeza i think this module complements really nice https://github.com/OCA/multi-company/pull/406 . Just incase you want to review. We would migrate to v15

Thanks

**Review by loida-vm — APPROVED** [review]
This module is very helpful!!
LGTM

Thanks.

**Pull request merged**
