### PR TITLE
[11.0][ADD] ir_actions_report_multi_company

### PR DESCRIPTION
**Pull request by astirpe**
This is a proposal to add module `ir_actions_report_multi_company` in branch 11.0.
The module allows to make printable reports multi-company aware.

It's the same module already proposed in https://github.com/OCA/multi-company/pull/36 for Odoo 10.0, but with the following differences:

- the `company_id` field is without a default value. See https://github.com/OCA/multi-company/pull/36#discussion_r159139362 for the reasoning.
- module is renamed from `ir_actions_report_xml_multi_company` to `ir_actions_report_multi_company` in order to make it more "11.0 compliant".

### CODE REVIEW

**Comment by andreparames** [comment]
:+1:

**Review by andreparames — APPROVED** [review]

**Review by pankk — APPROVED** [review]
Nice! Perhaps get rid of some of the copyright blocks as having it in just the manifest should be more than enough, but that should be up to the original author.

**Review by pankk — APPROVED** [review]

**Comment by astirpe** [comment]
@jbeficent @pedrobaeza is it ok to merge this old PR?

**Comment by pedrobaeza** [comment]
OK, although I haven't checked it.

/ocabot merge

**Comment by astirpe** [comment]
https://travis-ci.org/OCA/multi-company/jobs/568283560#L169
Perhaps a temporary failure? :thinking:

**Comment by pedrobaeza** [comment]
It seems so

**Comment by sbidoul** [comment]
You might also be interested in https://github.com/OCA/reporting-engine/pull/307

**Pull request merged**
