### PR TITLE
[15.0][MIG] mail_multicompany

### PR DESCRIPTION
**Pull request by ryanc-me**
No changes required

### CODE REVIEW

**Comment by ryanc-me** [comment]
Hey @pedrobaeza, pre-commit is failing at:

`ImportError: cannot import name 'formatargspec' from 'inspect' (/opt/hostedtoolcache/Python/3.11.0/x64/lib/python3.11/inspect.py)`

Is that an error on my side, or something with the pre-commit conf?

**Comment by pedrobaeza** [comment]
Rebase after #404

**Comment by houssine78** [comment]
Hi @ryanc-me could you please rebase your branch as requested by Pedro ?
thank you

**Review by houssine78 — APPROVED** [review]

**Comment by hb-webdev** [comment]
Anxiously waiting on `mail_multicompany` for Odoo.sh 15.0 to download from the Odoo App Store

**Comment by yboujraf** [comment]
Dear 

Any news when it will be released ?

Best Regards

**Comment by mof-landoo** [comment]
@ryanc-me any news about this PR? thanks

**Comment by ryanc-me** [comment]
Whoops, sorry about the delay here everyone! @pedrobaeza looks like all checks are passing now

**Review by mof-landoo — APPROVED** [review]

**Pull request merged**
