### PR TITLE
[16.0][ADD] purchase_sale_container_deposit_inter_company

### PR DESCRIPTION
**Pull request by santostelmo**
In `product_packaging_container_deposit`, product packaging container deposit lines added automatically by the system are flagged with (`is_container=True`).
That information needs to be propagated from the PO to the SO to allow the correct computation of the product packaging container deposit.

Depends:
- purchase_product_packaging_container_deposit:  https://github.com/OCA/purchase-workflow/pull/2034
- sale_product_packaging_container_deposit: https://github.com/OCA/sale-workflow/pull/2692

### CODE REVIEW

**Comment by cyrilmanuel** [comment]
shall be repush to check wheelhouse. update PR with minimal change shall retrigger correction ?

**Comment by legalsylvain** [comment]
hi @santostelmo. could you rebase ? thanks !

**Comment by santostelmo** [comment]
> hi @santostelmo. could you rebase ? thanks !

Rebased

**Review by cyrilmanuel — APPROVED** [review]

**Comment by cyrilmanuel** [comment]
Hii @legalsylvain , is it good for you  ?  :)

kind regards

**Comment by legalsylvain** [comment]
hi @cyrilmanuel. I don't use intercompany features. I'm not the good one for the review.

**Comment by cyrilmanuel** [comment]
hoo sorry @legalsylvain  :) 

perhaps @pedrobaeza  you could help us  to review / merge this PR ?

**Review by pedrobaeza — APPROVED** [review]
Quick code review, although I don't use this.

/ocabot merge nobump

**Pull request merged**
