### PR TITLE
[14.0] [FIX] purchase_sale_inter_company: wrong field

### PR DESCRIPTION
**Pull request by renda-dev**
This PR fixes a bug that was preventing the module to work properly.

Without this, an error would be raised every time that `action_confirm` is triggered.

### CODE REVIEW

**Comment by HekkiMelody** [comment]
Seems like the field in question existed on v12 but was changed on v14

https://github.com/OCA/OCB/commit/57f805f71e9357870dfc2498c5ef72ebd8ab7273#diff-55c6314416a6a400da6acd5018d161a55eeeb0e3008fec8828121e3dd12be0eb

**Review by HekkiMelody — APPROVED** [review]

**Comment by HekkiMelody** [comment]
The fix is fine.

Would recommend adding a test that covers this use case, since just executing this part of the code once would have caught the problem.

**Review by francesco-ooops — APPROVED** [review]
Functional ok!

**Review by HekkiMelody — APPROVED** [review]

**Pull request merged**
