### PR TITLE
[15.0] [MIG] base_multi_company

### PR DESCRIPTION
**Pull request by JasminSForgeFlow**
Standard Migration

@ForgeFlow

### CODE REVIEW

**Comment by LoisRForgeFlow** [comment]
For the records, this depends on the discussion being hold in v14 migration. https://github.com/OCA/multi-company/pull/270

**Comment by LoisRForgeFlow** [comment]
@rousseldenis Maybe you are interested on this one, this includes your last change in v14.

**Review by rousseldenis — APPROVED** [review]
Code review

**Review by LoisRForgeFlow — APPROVED** [review]
LGTM

**Pull request merged**
