### PR TITLE
[13.0][IMP] account_invoice_inter_company: propagate invoice payment reference

### PR DESCRIPTION
**Pull request by JordiMForgeFlow**

### CODE REVIEW

**Review by LoisRForgeFlow — APPROVED** [review]

**Review by GuillemCForgeFlow — APPROVED** [review]

**Review by AaronHForgeFlow — APPROVED** [review]
:+1:

**Review by LauraCForgeFlow — APPROVED** [review]
LGTM!

**Comment by pedrobaeza** [comment]
@carlos-lopez-tecnativa do you see it correct?

**Comment by pedrobaeza** [comment]
@JordiMForgeFlow next time, before doing all the fw-ports, wait for the first one to be merged, as if any change, now you have to propagate that change to all the opened PRs, multiplying the work.

**Review by carlos-lopez-tecnativa — APPROVED** [review]
LGTM

**Comment by JordiMForgeFlow** [comment]
@pedrobaeza I know, but as it was a clear change to me and I had to start focusing on other work I wanted to have them prepared before hand :)

**Pull request merged**
