### PR TITLE
[14.0] [MIG] account_bill_line_distribution

### PR DESCRIPTION
**Pull request by Murtaza-OSI**

### CODE REVIEW

**Review by max3903 — APPROVED** [review]

**Comment by max3903** [comment]
@Urvisha-OSI Can you fix this PR please?

**Comment by dreispt** [comment]
Tests are failing: https://github.com/OCA/multi-company/actions/runs/4312327256/jobs/7522749153#step:8:394

**Comment by max3903** [comment]
@Urvisha-OSI @Murtaza-OSI Can you fix the remaining failing tests? Do you need help, time or both?

**Comment by legalsylvain** [comment]
friendly reminder  @Murtaza-OSI

**Pull request closed without merging**
