### PR TITLE
[15.0][MIG] purchase_sale_inter_company

### PR DESCRIPTION
**Pull request by DhavalTforgeFlow**
Standard migration

@ForgeFlow 
Depends on 
- https://github.com/OCA/multi-company/pull/346

### CODE REVIEW

**Comment by gurneyalex** [comment]
I like the module a lot, but I would need to use it in the context of a service company, which does not have stock installed. Would you welcome a PR on top of this one to split the module in 2: one new module which has the core of the functionality but no dependency on  stock, and this module which only adds the bits required for stock management in the PO / SO synchronization? 

Or should we merge this module first and work on a separate PR afterwards?

**Comment by yankinmax** [comment]
@DhavalTforgeFlow can you pls add `test-requirements.txt` in a separate commit?
```
odoo-addon-account_invoice_inter_company @ git+https://github.com/OCA/multi-company@refs/pull/346/head#subdirectory=setup/account_invoice_inter_company
```

**Comment by yankinmax** [comment]
> I like the module a lot, but I would need to use it in the context of a service company, which does not have stock installed. Would you welcome a PR on top of this one to split the module in 2: one new module which has the core of the functionality but no dependency on stock, and this module which only adds the bits required for stock management in the PO / SO synchronization?
> 
> Or should we merge this module first and work on a separate PR afterwards?

@DhavalTforgeFlow can you pls give feedback on this

**Comment by yankinmax** [comment]
@DhavalTforgeFlow @gurneyalex 
This the PR introducing module **without dependency on `stock`**:
- [ ] https://github.com/OCA/multi-company/pull/370

**Comment by JuanyDForgeflow** [comment]
@DhavalTforgeFlow is there any udpate on this?

**Comment by DhavalTforgeFlow** [comment]
@JuanyDForgeflow I think, This module should be dependent on the stock and the module that @yankinmax has developed and this module should only contain stock related feature. I will do it once PR [https://github.com/OCA/multi-company/pull/370](https://github.com/OCA/multi-company/pull/370) gets approved/merged.

**Comment by yankinmax** [comment]
@DhavalTforgeFlow my idea was to have two separate modules:

1. https://github.com/OCA/multi-company/pull/370 -> `purchase_sale_inter_company`
2. https://github.com/OCA/multi-company/pull/371 -> `purchase_sale_stock_inter_company`

**Comment by DhavalTforgeFlow** [comment]
@yankinmax  @JuanyDForgeflow  Sorry, I have just noticed, It is already done.

**Comment by DhavalTforgeFlow** [comment]
Closing this PR as @yankinmax is splitting this into 2 modules.

**Pull request closed without merging**
