### PR TITLE
[14.0] [IMP] base_multi_company: remove 'no_company_ids' field

### PR DESCRIPTION
**Pull request by renda-dev**
As solved in https://github.com/odoo/odoo/pull/81344

### CODE REVIEW

**Comment by renda-dev** [comment]
<del>Fixing tests...</del>

Ready!

**Review by francesco-ooops — APPROVED** [review]
Functional ok

**Review by HekkiMelody — APPROVED** [review]
Code review, LGTM

**Comment by francesco-ooops** [comment]
@pedrobaeza looking forward to your opinion :)

**Pull request merged**
