### PR TITLE
[14.0][ADD] account_invoice_inter_company_sale

### PR DESCRIPTION
**Pull request by ilyasProgrammer**
Show partner's shipping address in counterpart invoice form.

### CODE REVIEW

**Comment by francesco-ooops** [comment]
@ilyasProgrammer rebase?

**Review by francesco-ooops — APPROVED** [review]
functional review ok!

**Comment by francesco-ooops** [comment]
@pedrobaeza what do you say? this is the continuation of https://github.com/OCA/multi-company/pull/377#issuecomment-1238231488

**Review by pedrobaeza — APPROVED** [review]

**Pull request merged**
