### PR TITLE
[IMP] account_invoice_inter_company add index

### PR DESCRIPTION
**Pull request by xavier-bouquiaux**
on large database, we need this index for performance

@Cedric-Pigeon

### CODE REVIEW

**Review by Cedric-Pigeon — APPROVED** [review]

**Review by chienandalu — COMMENTED** [review]
Can you share some metrics? (table size, perfomance improvements in read/write operations before and after...)

**Comment by elvise** [comment]
@xavier-bouquiaux can you share some metrics ?

**Comment by xavier-bouquiaux** [comment]
Sorry i can't <br/>
Internally we use tools like pg-hero which recommend indexes <br/>
After analysis we decide that this index was worth it <br/>
I'll check if we still have some metrics about performance <br/>

For our client, the table account-move-line has approx. 8 million line

Regards

xbo

**Review by chienandalu — APPROVED** [review]

**Comment by chienandalu** [comment]
Will forward port it?

**Pull request merged**
