### PR TITLE
[12.0] ADD module company_dependent_attribute

### PR DESCRIPTION
**Pull request by bealdav**
backport of https://github.com/OCA/multi-company/pull/162

### CODE REVIEW

**Comment by bealdav** [comment]
Please @rvalyi @legalsylvain @moylop260 could you make a review with the same module merged in v13 #162 ?

**Comment by legalsylvain** [comment]
hi, just a question, but is it possible to cherry pick commits ? (like when you port module, with format patch command) ? 
it will be more easy to review.

**Comment by bealdav** [comment]
you're right : DONE

**Review by legalsylvain — APPROVED** [review]
ow ! hard review ! ;-)
LGTM. Change review / no test.

thanks for the backport, I'll use it for sure.

**Comment by moylop260** [comment]
/ocabot merge

Since that it is a backport from an approved PR

**Pull request merged**
