### PR TITLE
[15.0][FIX] purchase_sale_inter_company: sync confirmed unlocked purchase upadtes

### PR DESCRIPTION
**Pull request by chienandalu**
fw from 

- #559 

When the purchase user updates the PO after the SO is generated and always if both are confirmed and unlocked, we sync the new lines to update the demand.

cc @Tecnativa TT46773

please review @pedrobaeza 

@francesco-ooops @aleuffre @renda-dev I started forwarding your `14.0` prs but the task isn't trivial as the module was split in v15

### CODE REVIEW

**Review by pedrobaeza — APPROVED** [review]

**Comment by francesco-ooops** [comment]
@chienandalu I tried testing on runboat, installing the module

do you know why there is only one company in the instance?

**Comment by chienandalu** [comment]
> do you know why there is only one company in the instance?

I guess you used the base runboat. If you use the full one, you'll find all the demo data.

**Comment by francesco-ooops** [comment]
@chienandalu ok, unrelated to this PR, but what module/application are the multi-company demo data related to?

**Comment by chienandalu** [comment]
I think that the demo data for Chicago goes with `stock`

**Review by francesco-ooops — APPROVED** [review]
Functional ok!

**Pull request merged**
