### PR TITLE
[16.0][MIG] res_company_active (from 12.0 to 16.0)

### PR DESCRIPTION
**Pull request by legalsylvain**
Classical migration.

### description

This module adds the possibility to archive companies by UI via the common "Action > Archive" button.

res_company_form

**Note**

A control is realized, to check if the disabled company is the current company
for active users.

validation_error

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Afaik, this is included in core

**Comment by legalsylvain** [comment]
> Afaik, this is included in core

Totally right. The active field is now in core.

However : 
- archive action is not possible in form view, because the field is not present
- the ribbon is not displayed
- the check to avoid to have users on disabled companies is not done.

see [diff commit](https://github.com/OCA/multi-company/pull/389/commits/ab5546b0bb48575f056671be1654b630bdb9f5c8#diff-1ea79960801cf1fbb805ff9f06d8c177bf7950cee47029b5c00f3dc8dd29d52cR1).

**Comment by pedrobaeza** [comment]
👍

**Review by bodedra — APPROVED** [review]
Functional reviewed. 👍

**Comment by legalsylvain** [comment]
@pedrobaeza. you set a :+1: but not via github. So the Pr is not approved. could you do it. (and merge if possible ;-))
thanks !

**Comment by pedrobaeza** [comment]
My thumb up was just to say OK to the reply of my comment, but it was not a review.

/ocabot migration res_company_active

**Review by desdelinux — APPROVED** [review]

**Comment by legalsylvain** [comment]
Hi maintainers : could you merge  this approved PR ?

**Pull request merged**
