### PR TITLE
[9.0][FIX] partner_multi_company: Fix hook on deactivated partners

### PR DESCRIPTION
**Pull request by lasley**
* Add domain to include both active and inactive partners into the install hook

Re #48

### CODE REVIEW

**Review by pedrobaeza — APPROVED** [review]

**Comment by lasley** [comment]
Suggestions in  #49 have been brought in here. Forgive the squash, it was easier to just bring the direct commit over instead of hashing out the diff just to squash again

**Review by StefanRijnhart — APPROVED** [review]

**Comment by pedrobaeza** [comment]
Travis is failing as demo data is not working. What I do for testing hooks is to set initial situation by SQL, and then call the hook.

**Review by elicoidal — APPROVED** [review]

**Comment by pedrobaeza** [comment]
@elicoidal please don't merge if I have commented that there's an error.

**Comment by elicoidal** [comment]
Oups sorry: I saw the 2 approved green and didnot see the comment.
May I suggest that if you have a blocking point you revert the approval to red in the future?

Do you want me to revert?

**Comment by pedrobaeza** [comment]
The best indicator is that Travis is red, and you shouldn't merge anything in red unless it's very justified, so no need for me to add a "Request changes" point. Just see that section. As the problem is in the tests, a new PR solving it is enough.

**Comment by StefanRijnhart** [comment]
Tests fixed here: https://github.com/OCA/multi-company/pull/70

**Comment by lasley** [comment]
It's just tests, I'll submit a PR today. I think that'd be cleaner than a revert

**Comment by lasley** [comment]
Orrrr. refresh the page and @StefanRijnhart already did it for me. Woot!

**Pull request merged**
