### PR TITLE
[15.0][MIG] mail_template_multi_company

### PR DESCRIPTION
**Pull request by JasminSForgeFlow**
Standard Migration

@ForgeFlow

### CODE REVIEW

**Comment by brechtverhaeghe** [comment]
Is this MR ready?

**Comment by JasminSForgeFlow** [comment]
> Is this MR ready?

yes

**Comment by wad11656** [comment]
Can this be merged and published to the Odoo store (for Odoo.sh)?

**Comment by hb-webdev** [comment]
Can this be merged and published to the Odoo store (for Odoo.sh)?

**Comment by LoisRForgeFlow** [comment]
Hi @hb-webdev could you drop your approval to help get it merged?

**Comment by oskardotglobal** [comment]
I tested this and can confirm it is working. How do we get this merged?

**Review by LoisRForgeFlow — APPROVED** [review]

**Pull request merged**
