### PR TITLE
[FIX] pep8 in product_autocpny and product_name_unique

### PR DESCRIPTION
**Pull request by bealdav**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
There are still a few issues:

```
./product_name_unique_per_company/__init__.py:18:75: W291 trailing whitespace
./product_autocompany/__init__.py:18:75: W291 trailing whitespace
./product_name_unique_per_company/product_name_unique_per_company.py:18:75: W291 trailing whitespace
./product_autocompany/product_autocompany.py:18:75: W291 trailing whitespace
```

**Comment by pedrobaeza** [comment]
Thanks :+1:

**Comment by bealdav** [comment]
Travis is OK, thanks for a review

**Comment by eLBati** [comment]
:+1:

**Pull request merged**
