### PR TITLE
IMP inv_inter_cpny: add partner_shipping_id field

### PR DESCRIPTION
**Pull request by bealdav**
@sebastienbeau

### CODE REVIEW

**Review by pedrobaeza — APPROVED** [review]

**Comment by pedrobaeza** [comment]
Please check pre-commit

**Comment by bealdav** [comment]
Yes online patch PR doesn't work well with precommit considerations

**Review by mourad-ehm — APPROVED** [review]

**Comment by bealdav** [comment]
Please @gurneyalex @jgrandguillaume @JordiBForgeFlow could you merge this trivial improvement ? Thanks a lot

**Pull request merged**
