### PR TITLE
[16.0][IMP] product_account_multicompany_default propagate product category accounts

### PR DESCRIPTION
**Pull request by santostelmo**
Propagate product category accounts from the current company to all
other companies where you have access rights.

### CODE REVIEW

**Review by cyrilmanuel — APPROVED** [review]
not an expert but LGTM

**Review by leemannd — APPROVED** [review]

**Review by yajo — CHANGES_REQUESTED** [review]
Thanks for the contribution. It looks pretty well. However, I can see no changes on README.

Since this impacts in the module functionality, please extend the description and usage sections. This way we'll know better how to test this functionally.

**Comment by santostelmo** [comment]
> Thanks for the contribution. It looks pretty well. However, I can see no changes on README.
> 
> Since this impacts in the module functionality, please extend the description and usage sections. This way we'll know better how to test this functionally.

Thanks for your review @yajo . I have updated README mentioning propagation of accounting fields on product category.

**Comment by cyrilmanuel** [comment]
Hi @yajo  it's Ok for you ?? can you merge this PR :)

**Comment by cyrilmanuel** [comment]
Hello @pedrobaeza, could you merge this PR ?

**Review by yajo — APPROVED** [review]
/ocabot merge minor

**Comment by gurneyalex** [comment]
@santostelmo can you check the failures on merge?

**Review by Saran440 — APPROVED** [review]
Code Review :+1:

**Comment by santostelmo** [comment]
> @santostelmo can you check the failures on merge?

Ci failures fixed. I increased unit test coverage.

**Pull request merged**
