### PR TITLE
[14.0][IMP] account_invoice_inter_company: Make locking of target invoices optional.

### PR DESCRIPTION
**Pull request by thomaspaulb**
In some cases people want to modify the invoice to cater for partial deliveries etc

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Please change commit message to comply with the guidelines: https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/CONTRIBUTING.rst#commit-message

- module name
- first line message shorter

**Comment by thomaspaulb** [comment]
@pedrobaeza Didn't yet know about that one, thanks! Modified.

**Review by pedrobaeza — APPROVED** [review]

**Review by christian-ramos-tecnativa — APPROVED** [review]

**Comment by thomaspaulb** [comment]
@aleuffre Can this one be merged?

**Comment by HekkiMelody** [comment]
> @aleuffre Can this one be merged?

Ah, I'm not a maintainer on this specific module, sorry!

**Comment by thomaspaulb** [comment]
@pedrobaeza Do you have merge rights here?

**Pull request merged**
