### PR TITLE
[10.0][ADD]mail_multicompany.

### PR DESCRIPTION
**Pull request by jesusVMayor**
This module adds company_id to the models ir.mail_server and mail.mail. Also inherits mail.mail create function to set the company mail_server.

### CODE REVIEW

**Comment by Cedric-Pigeon** [comment]
@jesusVMayor Looks great but could you add some unit tests ?

**Comment by Cedric-Pigeon** [comment]
@jesusVMayor I discovered some bugs. I am preparing a PR on your branch...

**Comment by Cedric-Pigeon** [comment]
https://github.com/comunitea/multi-company/pull/1

**Comment by Cedric-Pigeon** [comment]
@jesusVMayor Could you have a look at travis?

**Comment by ayahamdy123** [comment]
> @jesusVMayor I discovered some bugs. I am preparing a PR on your branch...
what bugs do you discover

**Pull request closed without merging**
