### PR TITLE
[16.0][MIG] mail_template_multi_company: Migration to 16.0

### PR DESCRIPTION
**Pull request by BT-anieto**
Includes the fix in https://github.com/OCA/multi-company/pull/485

### CODE REVIEW

**Comment by BT-anieto** [comment]
@Olivier-LAURENT Hi Olivier! Just mentioning you because you appear as a maintainer. Thx :)

**Review by BT-cmorales — APPROVED** [review]
LGTM

**Review by BT-aleonard — APPROVED** [review]
LGTM, thanks for migrating! :+1:

**Review by BT-dmoreno — APPROVED** [review]

**Comment by BT-anieto** [comment]
Good morning @pedrobaeza Could you take a look at this PR? [Olivier-LAURENT](https://github.com/Olivier-LAURENT) seems to not have activity in the past years and I do not find any general multi-company maintainers.

Thank you in advance

**Pull request merged**
