### PR TITLE
[13.0][MIG] mail_template_multi_company

### PR DESCRIPTION
**Pull request by astirpe**

### CODE REVIEW

**Review by yung-wang — APPROVED** [review]
Tested in V13 and it works fine

**Review by CasVissers-360ERP — APPROVED** [review]
Functional and minor technical review.

**Review by LoisRForgeFlow — APPROVED** [review]
Code reivew LGTM

**Comment by astirpe** [comment]
Can this one be merged?

**Comment by pedrobaeza** [comment]
Merging blindly seeing reviews:

/ocabot merge nobump

**Comment by pedrobaeza** [comment]
@astirpe please rebase an re-apply pre-commit

**Comment by astirpe** [comment]
@pedrobaeza done

**Pull request merged**
