### PR TITLE
[13.0] ADD module company_dependent_attribute

### PR DESCRIPTION
**Pull request by bealdav**
Display company_dependent state of fields in "ir.model.fields" view

company_dependent value of a field can be overrided in any module.
Then it can be difficult to guess this value in a odoo instance with a lot of modules.

This module is mainly intended for developers

Prefixed `property_` fields are supposed to be company_dependent fields.

screen1

the clothes do not make the man

### CODE REVIEW

**Comment by bealdav** [comment]
please @moylop260 @gurneyalex a small review for a small technical module

**Review by moylop260 — APPROVED** [review]
👍

**Review by legalsylvain — APPROVED** [review]
LGTM. code review / No test.
make sense.
Thanks !

**Review by rvalyi — APPROVED** [review]

**Comment by legalsylvain** [comment]
thanks. 
/ocabot merge

**Pull request merged**
