### PR TITLE
[13.0] account_invoice_inter_company: fw ports

### PR DESCRIPTION
**Pull request by chienandalu**
Forward port of last changes and tests

cc @Tecnativa TT26574

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Please check Travis

**Comment by pedrobaeza** [comment]
Travis is red, @chienandalu

**Comment by pedrobaeza** [comment]
Ouch, still red. Do you know why?

**Comment by chienandalu** [comment]
I think so.

**Comment by pedrobaeza** [comment]
No luck

**Comment by chienandalu** [comment]
Thanks for the contribution @PierrickBrun :smile:

**Comment by PierrickBrun** [comment]
> Thanks for the contribution @PierrickBrun smile

NP, I had trouble running pre-commit with dependencies conflict and i couldn't rebase from my PR. Do you mind fixing it ?

**Comment by chienandalu** [comment]
Yes, no problem :)

**Comment by chienandalu** [comment]
Looks like it still doesn't like it :/

**Comment by pedrobaeza** [comment]
Please squash. The patch is a bit ugly depending on other modules, but if it works, let's unblock this.

**Comment by chienandalu** [comment]
Rebased!

**Comment by pedrobaeza** [comment]
Now Travis is red

**Comment by chienandalu** [comment]
Green at last :)

**Review by pedrobaeza — APPROVED** [review]

**Pull request merged**
