### PR TITLE
[13.0][ADD+MIG] mail multicompany

### PR DESCRIPTION
**Pull request by ValentinVinagre**
Continue PR: https://github.com/OCA/multi-company/pull/104
ADD+MIG version 13.0
 @jesusVMayor and @Cedric-Pigeon I add your commits contributions.

### CODE REVIEW

**Comment by ValentinVinagre** [comment]
@HaraldPanten could you review?
Thanks

**Review by HaraldPanten — APPROVED** [review]
LGTM 👍

**Review by HaraldPanten — APPROVED** [review]
It looks better now 👍

**Review by Cedric-Pigeon — APPROVED** [review]
LGTM, Thanks.

**Comment by HaraldPanten** [comment]
@jgrandguillaume I think this one is ready to merge

**Pull request merged**
