### PR TITLE
[IMP] company_dependent_flag: icon position improved on company dependent fields

### PR DESCRIPTION
**Pull request by dora-jurcevic**

### CODE REVIEW

**Review by bealdav — APPROVED** [review]
Tested on project with several impact fields. 

Nice works. Thanks

**Comment by dora-jurcevic** [comment]
CSS style modified in order to display the building icon on the same line as the input field on the form. The two elements (the icon and the field) are now better aligned


BEFORE 
Screenshot from 2024-01-16 14-25-18

AFTER

Screenshot from 2024-01-16 14-24-11

**Review by legalsylvain — APPROVED** [review]
Hi. Interesting module I discover. Thanks for this important patch.

Note : maybe matter of taste, but I think the icon should be before the label, and not after. If so, it will be less confusing (because less close to the field to be entered)

**Comment by bealdav** [comment]
Thanks a lot @legalsylvain you're right it's better to be near label but it's harder and require more code because label is either near to the field or either before with `<div><label for="field"/></div>`.

Then this patch is a kind quick and welcome fix with very few code, then sure.

Other behavior needs other PR, you're right, but code could be more tricky

**Comment by bealdav** [comment]
Thanks a lot @legalsylvain

**Pull request merged**
