### PR TITLE
[11.0][FIX] account_multicompany_easy_creation: account code digits and currency ignored

### PR DESCRIPTION
**Pull request by eantones**
Account code digits and currency are overwrited by onchange_chart_template_id method

### CODE REVIEW

**Comment by rafaelbn** [comment]
@chienandalu @pedrobaeza take a look here please

**Comment by pedrobaeza** [comment]
For me both values must be removed as they are not possible to be selected when installing it normally (and in v12 code digits disappear from res.company).

**Comment by eantones** [comment]
@rafaelbn @pedrobaeza I needed to do this fix because my customer was not able to create companies with more than 6 digits, now he can and he already did it perfectly using 9 digits.
Independently that it makes no sense in v12, it does in v11 and since it's clearly a bug, it should be fixed. Thanks

**Comment by pedrobaeza** [comment]
That's the mistake: to create CoA with more than 6 digits. It's totally unneeded and will be conflicting on v11 or v12. This is the new myth to be doomed as the accounts per customer/supplier. Both aren't needed. The only remnant is for assets, and with latest changes to account_asset_management you mustn't create one account per asset as well. The rest is to swim against current...

**Comment by pedrobaeza** [comment]
For me, the patch is to remove the digits from the wizard, but my colleague @carlosdauden that created the module probably differs, as he doesn't think the same about the usefulness of the digits, so I let him to make the final call.

**Comment by eantones** [comment]
@pedrobaeza I agree, no need more than 6 digits, but, as often, it's not black and white, due to the complexity of my customer's accounting it's too risky to try to redefine everything in a switch off-switch on context, it takes time and in the meantime they should be able to keep their activities going on with more than 6 digits. Anyway and aside of that, there's a bug in the code and it must be fixed. Thanks!

**Comment by pedrobaeza** [comment]
Yeah, removing the field is another bugfix :wink:

**Comment by eantones** [comment]
Yes, it certainly is :-) but I have to solve my customer issues one way or another.

**Comment by pedrobaeza** [comment]
Yes, if you use a flexible deployment like Doodba, you can deploy with this PR included in it without the need of merging, so this discussion and the final answer from my colleague shouldn't block you.

**Comment by eantones** [comment]
Nothing blocks me, I already solved my customer problem using this PR. I just wanted to share the fix to others. Thanks

**Comment by pedrobaeza** [comment]
OK, let's wait what my colleague thinks.

**Comment by eantones** [comment]
Perfect :)

**Review by carlosdauden — APPROVED** [review]
Being in agreement with Pedro's arguments, I weigh pros and cons of this PR:
PROS | CONS
---- | ----
Help some users who use a different value in v11 | None (This change does not affect those who use 6 digits)

so for my part I approve the PR

**Comment by pedrobaeza** [comment]
OK, let's go then

/ocabot merge patch

**Pull request merged**
