### PR TITLE
[14.0] [MIG] account_multicompany_easy_creation

### PR DESCRIPTION
**Pull request by mariadforgeflow**
Standard migration to v14

### CODE REVIEW

**Review by RaulOForgeFlow — APPROVED** [review]
Functional review :+1:

**Comment by victoralmau** [comment]
Please, it is also necessary to add this change https://github.com/OCA/multi-company/pull/317 (already merged in v13) for the correct functioning of the module (so that the selected accounting template is applied and created all necessary records).

**Review by RaulOForgeFlow — APPROVED** [review]

**Review by antoniocanovas — APPROVED** [review]
Functional review Ok

**Comment by pedrobaeza** [comment]
This fix is also needed: #321

**Comment by victoralmau** [comment]
This fix https://github.com/OCA/multi-company/pull/321 has been modified and is already merged.

I think the correct thing to do would be to apply the mentioned commits separately (with cherry-pick for example) and at the end, add the migration commit only with the necessary changes.

**Comment by pedrobaeza** [comment]
Sorry, another patch to be integrated here: #327

**Review by victoralmau — APPROVED** [review]
Code review OK

**Pull request merged**
