### PR TITLE
[13.0][MIG] purchase_sale_stock_inter_company: Migration to version 13.0

### PR DESCRIPTION
**Pull request by carolinafernandez-tecnativa**
- Migration purchase_sale_stock_inter_company to v13.
- Split functionalities from purchase_sale_inter_company into new module purchase_sale_stock_inter_company as it is on version 15.0.
- Improve tests
- Handle pickings with lots/serials: Previously an intercompany picking with tracked products would simply
throw an error. With this fix, the method searches for a lot in the destination company
that matches the one in the source company (same name and same product).
A new lot is created by duplicating the original, if none is found.  Ref https://github.com/OCA/multi-company/commit/3ffe6de8a7578870a183b8b19d369232b05adb08

@Tecnativa
TT46194

@pedrobaeza @carlosdauden

### CODE REVIEW

**Comment by carolinafernandez-tecnativa** [comment]
WIP

**Comment by legalsylvain** [comment]
/ocabot migration purchase_sale_stock_inter_company

@carolinafernandez-tecnativa : you can set the draft status to the PR, until it is ready to review.

thanks !

**Comment by carolinafernandez-tecnativa** [comment]
Fixed error tests, ready for review

**Review by pedrobaeza — APPROVED** [review]

**Review by carlosdauden — APPROVED** [review]

**Pull request merged**
