### PR TITLE
[13.0][FIX] account_invoice_inter_company: Solved problems for created invoices

### PR DESCRIPTION
**Pull request by CarlosRoca13**
cc @Tecnativa TT22727

### CODE REVIEW

**Review by pedrobaeza — APPROVED** [review]
My only doubt is about writing in `name` field instead of `move_name`, but I remember that both are synchronized on validation.

**Comment by CarlosRoca13** [comment]
@pedrobaeza Can you pass me the code where this synchronization is done?

**Review by ps-tubtim — APPROVED** [review]
Code LGTM.

**Pull request merged**
