### PR TITLE
[16.0] [MIG] res_company_code

### PR DESCRIPTION
**Pull request by legalsylvain**
### Description

In a big multi-company context, users often use a code to indentify
the differents companies.

* This module adds ``code`` fields on company model.

res_company_form

This field is optional, but should be unique, if defined.

* This code will prefix the name, in the Odoo Switch Company Menu widget:

switch_company_menu

* this module also change the order of the companies, ordering by code, then by company name. (instead of by sequence, then by name). It so hides the now useless field sequence.

res_company_tree

### CODE REVIEW

**Comment by rvalyi** [comment]
PR #390 was merged, could you rebase?

**Comment by legalsylvain** [comment]
> PR https://github.com/OCA/multi-company/pull/390 was merged, could you rebase?

Done.

**Comment by legalsylvain** [comment]
This one is ready to review.
CC : other contributors : @kirca, @kevinkhao, @anasuarez1

**Comment by kirca** [comment]
@legalsylvain LGTM

**Comment by legalsylvain** [comment]
@kirca thanks for your review. Could make an approval via github ? 
thanks !

**Comment by kirca** [comment]
@legalsylvain I would do it gladly but I don't see it as an option. Do you maybe need to request a review from me first?

**Comment by legalsylvain** [comment]
> @kirca

you have to click on "File Changes" > click on button "Review Changes" > then comment / approve or "Request Changes".

Thanks !

**Review by kirca — APPROVED** [review]

**Pull request merged**
