### PR TITLE
[UPD] #10761 Activity instead of hard raise

### PR DESCRIPTION
**Pull request by thomaspaulb**

### CODE REVIEW

**Review by ddejong-therp — APPROVED** [review]
LGTM

**Review by HekkiMelody — COMMENTED** [review]
Code review, LGTM.

PR is still in draft.
Could I ask you to adjust the commit history according to the OCA guidelines? https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/CONTRIBUTING.rst#commit-message

Thank you!

**Comment by thomaspaulb** [comment]
@aleuffre Done and moved out of Draft.

**Review by HekkiMelody — APPROVED** [review]

**Pull request merged**
