### PR TITLE
[14.0][IMP] product_supplierinfo_intercompany: create intercompany pr…

### PR DESCRIPTION
**Pull request by ilyasProgrammer**
…icelist based on product category or for all products.

### CODE REVIEW

**Comment by elvise** [comment]
Hi, @PierrickBrun @kevinkhao @sebastienbeau according to the module roadmap:
"Currently the module only supports products pricelist items, in the future it will support managing categories and global items."

This PR wants to implement these features, any suggestions are welcome! :)

**Review by elvise — APPROVED** [review]
Functional review: OK!

**Comment by elvise** [comment]
@pedrobaeza please check this improve according the roadmap :)

**Comment by pedrobaeza** [comment]
I don't know this module.

**Comment by elvise** [comment]
> I don't know this module.

Ok thanks! 
@PierrickBrun @kevinkhao can you help us for the review ? 
Thanks in advance ✌🏻

**Review by francesco-ooops — APPROVED** [review]
Functional review is good

**Comment by francesco-ooops** [comment]
@OCA/intercompany-maintainers can you take a look? thanks!

**Review by PierrickBrun — APPROVED** [review]
code LGTM, thanks

Do not forget to remove the text in the ROADMAP.rst

**Comment by francesco-ooops** [comment]
@PierrickBrun thank you for the heads up, can you suggest how to update description as well?

**Comment by elvise** [comment]
@kevinkhao @sebastienbeau any feedback?

**Comment by francesco-ooops** [comment]
> code LGTM, thanks
> 
> Do not forget to remove the text in the ROADMAP.rst

done!

@OCA/intercompany-maintainers good for merge?

**Comment by elvise** [comment]
Hi @PierrickBrun for your point of view, is it ready for merge ?

**Comment by PierrickBrun** [comment]
> Hi @PierrickBrun for your point of view, is it ready for merge ?

All good

**Comment by elvise** [comment]
hi @pedrobaeza , @PierrickBrun is the author of the module and we have the green light from him, what do you think can we merge ?

**Comment by pedrobaeza** [comment]
Merging blindly based on the existing reviews

/ocabot merge patch

**Pull request merged**
