### PR TITLE
[13.0][MIG] res company code

### PR DESCRIPTION
**Pull request by kirca**
Migration of `res_company_code`

### CODE REVIEW

**Comment by luisg123v** [comment]
Hi @kirca,

Could you rebase so your PR gets green, please?

**Comment by kirca** [comment]
Hi @luisg123v , done. But code coverage check are failing now

**Review by luisg123v — APPROVED** [review]
:+1:

@moylop260 what do you think?

**Review by moylop260 — APPROVED** [review]
👍 
LGTM it is a migration of a useful module

**Pull request merged**
