### PR TITLE
[16.0][FIX] account_invoice_inter_company : partner_shipping_id shouldn't b…

### PR DESCRIPTION
**Pull request by metaminux**
…e propagated to supplier invoices

  fixes OCA/multi-company#651

### CODE REVIEW

**Comment by metaminux** [comment]
Hi @alexis-via and @pedrobaeza,

There is no maintainer on this module. Can I have your feedback on this PR ? Thanks.

**Review by Kev-Roche — APPROVED** [review]
LGTM

**Review by pedrobaeza — APPROVED** [review]

**Comment by metaminux** [comment]
Hi @alexis-via and @pedrobaeza,

Can one of you merge this approved PR ?

Regards,

**Pull request merged**
