### PR TITLE
[BKP][14.0] product_tax_multicompany_default: Overwrite taxes instead of adding it

### PR DESCRIPTION
**Pull request by Shide**
Backporting Commit https://github.com/OCA/multi-company/commit/afb5733aa2a165355880b4923125709453cb802c done in v16 migration.

Same backport as https://github.com/OCA/multi-company/pull/447 PR

MT-2121 @moduon @rafaelbn @carlosdauden

### CODE REVIEW

**Review by yajo — APPROVED** [review]

**Review by rafaelbn — APPROVED** [review]
👍 FIX

STR v14: same as 15 and 16
STR v15: https://www.loom.com/share/742bfd679c864797b89743ef6075d0f1
STR v16: https://www.loom.com/share/0f50c6ee2dd04c0f80390a2bd94362e9

**Comment by Shide** [comment]
Cherry picked https://github.com/OCA/multi-company/pull/447/commits/9645c0c54c5cc45649d274fde607155e2cb998c9

**Review by carlosdauden — APPROVED** [review]

**Comment by pedrobaeza** [comment]
Waiting for the 16.0 branch comments.

**Comment by rafaelbn** [comment]
Please, all comments attended 😄 👍  Could we merge the FIX. Actually this module is unusable! Thank you!

**Comment by etobella** [comment]
Tests are failing. Can you review them?

**Comment by yajo** [comment]
I couldn't get to reproduce the failure locally, so I delcared the module as rebel. It's ✅  now.

**Review by yajo — APPROVED** [review]

**Comment by yajo** [comment]
@etobella could you (or somebody else) merge please? This is already approved and ✅

**Pull request merged**
