### PR TITLE
[14.0][MIG]account_payment_other_company.

### PR DESCRIPTION
**Pull request by hpatelserpentcs**
Migrated module account_payment_other_company in v14.

### CODE REVIEW

**Comment by patrickrwilson** [comment]
@hpatelserpentcs Please check Travis errors. Thanks.

**Comment by hpatelserpentcs** [comment]
> @hpatelserpentcs Please check Travis errors. Thanks.

Travis issue is :No matching distribution found for odoo14-addon-account_invoice_consolidated
    because this module depend on account_invoice_consolidated module  and this is not in 14.0 addons [https://github.com/OCA/multi-company/pull/284]

**Comment by patrickrwilson** [comment]
@hpatelserpentcs The dependency has been merged. Can you take a look at this again and make green? Thanks.

**Comment by hpatelserpentcs** [comment]
> @hpatelserpentcs The dependency has been merged. Can you take a look at this again and make green? Thanks.

Yes, I will update it.
Thanks

**Pull request closed without merging**
