### PR TITLE
[17.0][MIG] mail_multicompany

### PR DESCRIPTION
**Pull request by SodexisTeam**

### CODE REVIEW

**Review by amkarthik — APPROVED** [review]

**Review by atchuthan — APPROVED** [review]
code review :+1:

**Comment by novamilky** [comment]
@dreispt What's the status here?

**Comment by pomazanbohdan** [comment]
@dreispt 
Would you be so kind as to repeat the note to the bot?
> /ocabot migration mail_multicompany

**Comment by atchuthan** [comment]
> @SodexisTeam Would you be so kind as to repeat the note to the bot?
> 
> > /ocabot migration mail_multicompany

@dreispt please add it to bot.

**Comment by alexeirivera87** [comment]
Hello @SodexisTeam 

Why was this field removed from fetchmail.server ? I am sure there was a reason.

https://github.com/OCA/multi-company/blob/16.0/mail_multicompany/models/fetchmail.py

regards

**Comment by amkarthik** [comment]
@alexeirivera87 
We haven't removed any. The field is added in v16 after our migration to v17.
Please refer the attached screenshot.
Commit Ref: https://github.com/OCA/multi-company/commit/4dfec6a9c4010ee11579cf2d904dc45d1e4c7866

image

Thanks

**Comment by alexeirivera87** [comment]
@SodexisTeam 

Thank you for the clarification. I noticed the field is missing in recent versions, not only in v17, so would need to add it, so incoming email servers behavior similar to outgoing ones.

regards

**Pull request merged**
