### PR TITLE
[IMP] account_invoice_inter_company: 10 times faster counterpart invo…

### PR DESCRIPTION
**Pull request by ilyasProgrammer**
…ice creation.

### CODE REVIEW

**Review by francesco-ooops — APPROVED** [review]
Tested locally, time significantly decreased!

image

@OCA/intercompany-maintainers can you take a look?

**Review by pedrobaeza — CHANGES_REQUESTED** [review]
Speed here is not the only parameter. We want to do it through Form to get all the needed values, including extension modules that you can't handle at this level.

**Comment by elvise** [comment]
> Speed here is not the only parameter. We want to do it through Form to get all the needed values, including extension modules that you can't handle at this level.

@pedrobaeza Got it, any suggestion ? 
Right now for 15 invoices it took around 12 hours and that's not reasonable.

**Comment by pedrobaeza** [comment]
It seems something incorrect indeed, as the same `Form` is used for all the invoice lines. I don't think it's something of this base.

**Comment by ilyasProgrammer** [comment]
@pedrobaeza can play_onchanges() help here instead of Form ?

**Comment by elvise** [comment]
> It seems something incorrect indeed, as the same Form is used for all the invoice lines. I don't think it's something of this base.

@pedrobaeza are you assuming that the problem is not with this module?

**Comment by pedrobaeza** [comment]
Not easily, as you don't know all the possible ramifications. `onchange_helper` does it, but if you get that degraded performance, it's due to these onchanges, so you will get similar results or not the whole dependency chain.

**Pull request closed without merging**
