### PR TITLE
[10.0] fix automated tests

### PR DESCRIPTION
**Pull request by SimoRubi**
Fix https://github.com/OCA/multi-company/issues/188

### CODE REVIEW

**Comment by SimoRubi** [comment]
@OCA/intercompany-maintainers any idea why Travis can't build the Odoo environment?
Error is:
```
Collecting sqlalchemy
  Downloading SQLAlchemy-1.3.15.tar.gz (6.1 MB)
  Installing build dependencies ... -\done
  Getting requirements to build wheel ... done
ERROR: Exception:
Traceback (most recent call last):
  File "/home/travis/virtualenv/python2.7.13/lib/python2.7/site-packages/pip/_internal/cli/base_command.py", line 186, in _main
    status = self.run(options, args)
  File "/home/travis/virtualenv/python2.7.13/lib/python2.7/site-packages/pip/_internal/commands/install.py", line 331, in run
    resolver.resolve(requirement_set)
  File "/home/travis/virtualenv/python2.7.13/lib/python2.7/site-packages/pip/_internal/legacy_resolve.py", line 177, in resolve
    discovered_reqs.extend(self._resolve_one(requirement_set, req))
  File "/home/travis/virtualenv/python2.7.13/lib/python2.7/site-packages/pip/_internal/legacy_resolve.py", line 333, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/home/travis/virtualenv/python2.7.13/lib/python2.7/site-packages/pip/_internal/legacy_resolve.py", line 282, in _get_abstract_dist_for
    abstract_dist = self.preparer.prepare_linked_requirement(req)
  File "/home/travis/virtualenv/python2.7.13/lib/python2.7/site-packages/pip/_internal/operations/prepare.py", line 516, in prepare_linked_requirement
    req, self.req_tracker, self.finder, self.build_isolation,
  File "/home/travis/virtualenv/python2.7.13/lib/python2.7/site-packages/pip/_internal/operations/prepare.py", line 95, in _get_prepared_distribution
    abstract_dist.prepare_distribution_metadata(finder, build_isolation)
  File "/home/travis/virtualenv/python2.7.13/lib/python2.7/site-packages/pip/_internal/distributions/sdist.py", line 38, in prepare_distribution_metadata
    self._setup_isolation(finder)
  File "/home/travis/virtualenv/python2.7.13/lib/python2.7/site-packages/pip/_internal/distributions/sdist.py", line 96, in _setup_isolation
    reqs = backend.get_requires_for_build_wheel()
  File "/home/travis/virtualenv/python2.7.13/lib/python2.7/site-packages/pip/_vendor/pep517/wrappers.py", line 152, in get_requires_for_build_wheel
    'config_settings': config_settings
  File "/home/travis/virtualenv/python2.7.13/lib/python2.7/site-packages/pip/_vendor/pep517/wrappers.py", line 255, in _call_hook
    raise BackendUnavailable(data.get('traceback', ''))
BackendUnavailable
Traceback (most recent call last):
  File "/home/travis/maintainer-quality-tools/travis/clone_oca_dependencies", line 137, in <module>
    run(deps_checkout_dir, build_dir)
  File "/home/travis/maintainer-quality-tools/travis/clone_oca_dependencies", line 122, in run
    subprocess.check_call(command)
  File "/opt/python/2.7.13/lib/python2.7/subprocess.py", line 186, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['pip', 'install', '--no-binary', 'pycparser', '-Ur', '/home/travis/dependencies/server-tools/requirements.txt']' returned non-zero exit status 2
The command "travis_install_nightly" failed and exited with 1 during .
Your build has been stopped.
```
But in my local machine I have no problem in executing command `pip install --no-binary pycparser -Ur server-tools/requirements.txt`

**Comment by SimoRubi** [comment]
@OCA/intercompany-maintainers can someone please have a look at these changes?
Thanks!

**Comment by SimoRubi** [comment]
@OCA/intercompany-maintainers can someone please have a look at these changes?

@pedrobaeza this is why Travis was still red after https://github.com/OCA/multi-company/pull/118#issuecomment-565982162, now rebasing on this would make it :green_circle:

**Review by pedrobaeza — APPROVED** [review]
I'm not using anymore 10.0, and I think the switch to pip is not needed, but I won't block and give you a hand for continuing this

**Comment by SimoRubi** [comment]
@OCA/intercompany-maintainers can this be merged?
This is blocking (at least) https://github.com/OCA/multi-company/pull/118

**Review by astirpe — APPROVED** [review]

**Review by rousseldenis — APPROVED** [review]

**Pull request merged**
