### PR TITLE
[14.0][FIX] purchase_sale_inter_company: fix demo data

### PR DESCRIPTION
**Pull request by HekkiMelody**
Just changing these fields to make it easier to test the module.

Technically a bug in "stock" module's demo data. Contact Jeff Lawson is also the "address" of warehouse "Chicago 1".
The fields property_stock_customer and supplier are set to "Inter-warehouse transit" on Jeff Lawson for company San Francisco and not for company Chicago as it should be.

Since there are no routes set for location "Inter-warehouse transit", creating an inter-company PO from Chicago to SF fails; when the inter-company SO is automatically created, with delivery address towards the Chicago Warehouse i.e. Jeff Lawson, the creation of the SO's picking fails as there is no route available.

### CODE REVIEW

**Comment by francesco-ooops** [comment]
@pedrobaeza anything against? it's too late to fix it on 14 demo data

**Review by pedrobaeza — COMMENTED** [review]
Well, the proper final solution is to not use demo data at all. Do you have the same problem if you create a partner on the fly for tests instead of using `stock.res_partner_address_41`?

**Comment by francesco-ooops** [comment]
@pedrobaeza demo data are useful for functional testing and bug reporting :)

**Comment by pedrobaeza** [comment]
Yes, that's its purpose. Not for tests.

**Comment by HekkiMelody** [comment]
There may be a misunderstanding here. Automated tests/unit tests already work well.

This change is purely to make functional testing easier.

**Review by pedrobaeza — APPROVED** [review]
OK then.

**Pull request merged**
