### PR TITLE
MIGR 14.0 company_dependent_attribute

### PR DESCRIPTION
**Pull request by bealdav**
screen1

screen2

### CODE REVIEW

**Review by PierrickBrun — APPROVED** [review]

**Review by kevinkhao — APPROVED** [review]

**Comment by legalsylvain** [comment]
Thanks for the work. 
However, for the futur, could you follow OCA guidelines, regarding OCA migration, specially preserving history ?

Ref : https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-14.0

**Comment by bealdav** [comment]
I followed it and merged bots commits into a single one as requested by Pedro bot

**Comment by legalsylvain** [comment]
;-)
weird, original authors has been lost in that operation.
anyway, not a big deal.

**Comment by pedrobaeza** [comment]
Hey, I haven't requested that this time, but anyway, the squashing doesn't replace authorship if you do it properly. If you have doubts in the process, please ping me and I assist you.

**Comment by bealdav** [comment]
Original author were bots. I hope they'll forgive me to have stolen their authorships in a really small commit. I'll pay attention for the future, thanks

**Pull request merged**
