### PR TITLE
[8.0] account_invoice_inter_company

### PR DESCRIPTION
**Pull request by chafique-delli**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Isn't better to call this `base_inter_company`, as is the base for the other modules as stated in https://github.com/OCA/maintainer-tools/blob/master/CONTRIBUTING.md#modules?

**Comment by chafique-delli** [comment]
@pedrobaeza ,
The name 'base_inter_company' is not precise enough about the function of the module.

**Comment by pedrobaeza** [comment]
Well, you're right that it's not enough precise. OK, let's go for this one, but the README needs to be redone with new split

**Comment by sebastienbeau** [comment]
It's ok for me, tested and running in production :+1:

**Comment by bealdav** [comment]
:+1:

**Pull request merged**
