### PR TITLE
[14.0][ADD] mrp_multi_company

### PR DESCRIPTION
**Pull request by rousseldenis**
Includes:

- [ ] #271

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Shouldn't it be `mrp_bom_multi_company`?

**Comment by rousseldenis** [comment]
> Shouldn't it be `mrp_bom_multi_company`?

I thought about it but my first approach was to see if including only boms is sufficent.

Maybe this one can grew to include missing features if needed

**Comment by pedrobaeza** [comment]
Even if adding for example route multi-company capability, I think that should be other module for not getting a very big one difficult to maintain. About BOMs, you have a hard task assuring the integrity of all components through the companies...

**Comment by rousseldenis** [comment]
> About BOMs, you have a hard task assuring the integrity of all components through the companies...

Of course, but that's product manager job (they currently doing it). I had idea to put the company_ids on boms directly (not related) but that should have been the bottleneck. Through related, the job is done on product and that's all.

**Pull request closed without merging**
